version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - '8000:80'
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    command: >
      sh -c "php artisan migrate:fresh --seed --force &&
           php artisan queue:work --daemon &
           apache2-foreground"
  soketi:
    image: quay.io/soketi/soketi:1.4-16-debian
    container_name: soketi
    restart: unless-stopped
    environment:
      SOKETI_DEBUG: '${SOKETI_DEBUG:-1}'
      SOKETI_METRICS_SERVER_PORT: 9601
      SOKETI_DEFAULT_APP_ID: '${PUSHER_APP_ID}'
      SOKETI_DEFAULT_APP_KEY: '${PUSHER_APP_KEY}'
      SOKETI_DEFAULT_APP_SECRET: '${PUSHER_APP_SECRET}'

    ports:
      - '${PUSHER_PORT:-6001}:6001'
      - '${PUSHER_METRICS_PORT:-9601}:9601'

    
  
   
    


